### ISSUE TITLE
install.ps1 issues

### ISSUE THREAD

**Issue by UmBsublime** [nblagoev/Gmail.ps#1]
## When I try to install your module with the install.ps1 script i get this error.

C:\Users\Gamer\Documents\GitHub\Gmail.ps [master]> .\install.ps1
Import-Module : The 'C:\Users\Gamer\Documents\WindowsPowerShell\Modules\Gmail.p
s\Gmail.ps.psd1' module cannot be imported because its manifest contains one or
 more members that are not valid. The valid manifest members are ('ModuleToProc
ess', 'NestedModules', 'GUID', 'Author', 'CompanyName', 'Copyright', 'ModuleVer
sion', 'Description', 'PowerShellVersion', 'PowerShellHostName', 'PowerShellHos
tVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'Re
quiredModules', 'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'Priv
ateData', 'RequiredAssemblies', 'ModuleList', 'FileList', 'FunctionsToExport',
'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). Remove the members
that are not valid ('RootModule'), then try to import the module again.
At C:\Users\Gamer\Documents\GitHub\Gmail.ps\install.ps1:65 char:18
-     Import-Module <<<<  -Name $Destination\Gmail.ps
  - CategoryInfo          : InvalidData: (C:\Users\Gamer...s\Gmail.ps.psd1:
    String) [Import-Module], InvalidOperationException
  - FullyQualifiedErrorId : Modules_InvalidManifestMember,Microsoft.PowerShe
    ll.Commands.ImportModuleCommand
## Gmail.ps is installed and ready to use

Maybe i'm doing it wrong or missing some dependencies that are not mentioned. I haven't really looked into this issue since I currently don't have much powershell knowledge.

**Comment by UmBsublime** [comment]
even when i try to load the module manualy with PS> load-module gmail.psm1 it doesnt work. I get this error:

Unable to find type [PSCredential]: make sure that the assembly containing this
 type is loaded.
At C:\Users\Gamer\Documents\WindowsPowerShell\Modules\Gmail.ps\Gmail.ps.psm1:91
1 char:31
-     [OutputType([PSCredential] <<<< )]
  - CategoryInfo          : InvalidOperation: (PSCredential:String) [], Pare
    ntContainsErrorRecordException
  - FullyQualifiedErrorId : TypeNotFound

Import-Module : The specified module '.\Gmail.ps.psm1' was not loaded because n
o valid module file was found in any module directory.
At line:1 char:14
- Import-Module <<<<  .\Gmail.ps.psm1
  - CategoryInfo          : ResourceUnavailable: (.\Gmail.ps.psm1:String) [I
    mport-Module], FileNotFoundException
  - FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm
    ands.ImportModuleCommand

**Comment by nblagoev** [comment]
What version of PowerShell are you using? Try to fetch the v2-compat branch and install from it. I changed that RootModule key in the manifest, seems it's new for v3

**Comment by UmBsublime** [comment]
I will try this when ever I have some free time.

Thank you for your fast response

Charles
