### ISSUE TITLE
Message Body is empty.

### ISSUE THREAD

**Issue by 1DontEx1st** [nblagoev/Gmail.ps#2]
I want to use gmail.ps to parse some of the messages in my inbox, but it doesn't seem to pull the Body. I can see pretty much every other field (Headers, From, To, etc.), so I wonder if this is part of the work-in-progress?

Thanks!

**Comment by nblagoev** [comment]
The message's body and attachments are downloaded only if you specify the -Prefetch parameter to Get-Message. Did you try that?

**Comment by 1DontEx1st** [comment]
Nope, I didn't have a clear understanding of the Prefetch parameter (or the use of Receive-Message, which I'll now use within a message loop). Thanks for the quick response, and for the excellent module!
