### ISSUE TITLE
Update-Message : Parameter set cannot be resolved using the specified named parameters.

### ISSUE THREAD

**Issue by Kristian-Aadal-Jensen** [nblagoev/Gmail.ps#3]
First off - very nice, lightweight, scripting opportunities - couldn't find any other way of getting the body of the mails so effortlessly.

Maybe not a bug - but I tried to find the problem other places without luck.
Pretty much using the Readme.md example I am getting the error as shown above.

script is:
$secpasswd = ConvertTo-SecureString "---" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ("---", $secpasswd)

Invoke-GmailSession -Credential $mycreds -ScriptBlock {
    param($gmail)
    $inbox = $gmail | Get-Mailbox
    $messages = $inbox | Get-Message | Select-Object -Last 10
    foreach ($msg in $messages) {
        $msg | Update-Message -Unread
    }
}

Am I doing it wrong?

**Comment by nblagoev** [comment]
Hello, Kristian! Thank you for the kind words. Yes it is a bug, the way I made the parameter sets for Update-Message was causing PowerShell to forbid the usage of -Read, -Unread, -Star and -Unstar separately. It's fixed now, please pull the **master** branch again to update the module.

**Comment by Kristian-Aadal-Jensen** [comment]
Cool thanks - and thanks again for the first class tool.
